-- [[ ===================================================== ]] --
-- [[               MH Parking V2 by MaDHouSe79             ]] --
-- [[ ===================================================== ]] --
Config.Vehicles = {
    [437538602] = { model = "speeder2", name = "Speeder Yacht", brand = "Pegassi", category = "boats" },
    [191916658] = { model = "streamer216", name = "Streamer216", brand = "Mammoth", category = "planes" },
    [-692292317] = { model = "chernobog", name = "Chernobog", brand = "HVY", category = "military" },
    [-2100640717] = { model = "tug", name = "Tug", brand = "Buckingham", category = "boats" },
    [2123327359] = { model = "prototipo", name = "X80 Proto", brand = "Grotti", category = "super" },
    [729783779] = { model = "slamvan", name = "Slam Van", brand = "Vapid", category = "muscle" },
    [-1149725334] = { model = "italirsx", name = "Itali RSX", brand = "Progen", category = "sports" },
    [850565707] = { model = "bjxl", name = "BeeJay XL", brand = "Karin", category = "suvs" },
    [1077420264] = { model = "velum2", name = "Velum 5-seater", brand = "JoBuilt", category = "planes" },
    [2035069708] = { model = "esskey", name = "Esskey", brand = "Pegassi", category = "motorcycles" },
    [-120287622] = { model = "journey", name = "Journey", brand = "Zirconium", category = "vans" },
    [-452604007] = { model = "rt3000", name = "RT3000", brand = "Dinka", category = "sports" },
    [1141395928] = { model = "comet7", name = "Comet", brand = "S2 Cabrio", category = "sedans" },
    [295054921] = { model = "annihilator2", name = "Annihilator Stealth", brand = "Western Company", category = "helicopters" },
    [1075432268] = { model = "swift2", name = "Swift Deluxe", brand = "Buckingham", category = "helicopters" },
    [-2072933068] = { model = "coach", name = "Dashound", brand = "Brute", category = "service" },
    [-1744505657] = { model = "impaler4", name = "Impaler Nightmare", brand = "Vapid", category = "muscle" },
    [1507916787] = { model = "picador", name = "Picador", brand = "Cheval", category = "muscle" },
    [-536105557] = { model = "ratel", name = "Ratel", brand = "Vapid", category = "offroad" },
    [2134119907] = { model = "dukes3", name = "Beater Dukes", brand = "Imponte", category = "muscle" },
    [1336514315] = { model = "gauntlet6", name = "Hotring Hellfire", brand = "Bravado", category = "sports" },
    [338562499] = { model = "vacca", name = "Vacca", brand = "Pegassi", category = "super" },
    [2067820283] = { model = "tyrus", name = "Tyrus", brand = "Progen", category = "super" },
    [1896491931] = { model = "moonbeam2", name = "Moonbeam Custom", brand = "Declasse", category = "vans" },
    [-1855505138] = { model = "rhinehart", name = "Rhinehart", brand = "Übermacht", category = "sedans" },
    [-1763675285] = { model = "l35", name = "Walton L35", brand = "Declasse", category = "offroad" },
    [-810318068] = { model = "speedo", name = "Speedo", brand = "Vapid", category = "vans" },
    [-478639183] = { model = "impaler5", name = "Impaler SZ", brand = "Declasse", category = "sedans" },
    [886810209] = { model = "stromberg", name = "Stromberg", brand = "Ocelot", category = "sportsclassics" },
    [634118882] = { model = "baller4", name = "Baller LE LWB", brand = "Gallivanter", category = "suvs" },
    [1069929536] = { model = "bobcatxl", name = "Bobcat XL Open", brand = "Vapid", category = "vans" },
    [387748548] = { model = "hauler2", name = "Hauler Custom", brand = "Jobuilt", category = "commercial" },
    [-915704871] = { model = "dominator2", name = "Pißwasser Dominator", brand = "Vapid", category = "muscle" },
    [-441209695] = { model = "dominator9", name = "Dominator GT", brand = "Vapid", category = "muscle" },
    [1394036463] = { model = "cargobob3", name = "Cargobob", brand = "Western Company", category = "helicopters" },
    [-1232836011] = { model = "le7b", name = "RE-7B", brand = "Annis", category = "super" },
    [867467158] = { model = "dinghy4", name = "Dinghy Yacht", brand = "Nagasaki", category = "boats" },
    [-654498607] = { model = "brigham", name = "Brigham", brand = "Albany", category = "muscle" },
    [-1479664699] = { model = "brawler", name = "Brawler", brand = "Annis", category = "offroad" },
    [223240013] = { model = "cheetah2", name = "Cheetah Classic", brand = "Grotti", category = "sports" },
    [353883353] = { model = "polmav", name = "Police Maverick", brand = "Buckingham", category = "emergency" },
    [1265391242] = { model = "hakuchou", name = "Hakuchou", brand = "Shitzu", category = "motorcycles" },
    [276773164] = { model = "dinghy2", name = "Dinghy 4-Seater", brand = "Nagasaki", category = "boats" },
    [-64075878] = { model = "kanjosj", name = "Kanjo SJ", brand = "Dinka", category = "coupes" },
    [408192225] = { model = "turismor", name = "Turismo R", brand = "Grotti", category = "super", backengine = true },
    [272929391] = { model = "tempesta", name = "Tempesta", brand = "Pegassi", category = "super" },
    [83136452] = { model = "rebla", name = "Rebla GTS", brand = "Übermacht", category = "suvs" },
    [736902334] = { model = "buffalo2", name = "Buffalo S", brand = "Bravado", category = "sports" },
    [-165394758] = { model = "torero2", name = "Torero XO", brand = "Pegassi", category = "super" },
    [867799010] = { model = "pariah", name = "Pariah", brand = "Ocelot", category = "sports" },
    [-1696146015] = { model = "bullet", name = "Bullet", brand = "Vapid", category = "super", backengine = true },
    [-682211828] = { model = "buccaneer", name = "Buccaneer", brand = "Albany", category = "muscle" },
    [-1763555241] = { model = "microlight", name = "Ultralight", brand = "Unknown", category = "planes" },
    [-631760477] = { model = "massacro2", name = "Massacro Racecar", brand = "Dewbauchee", category = "sports" },
    [788045382] = { model = "sanchez", name = "Sanchez Livery", brand = "Maibatsu", category = "motorcycles" },
    [470404958] = { model = "baller5", name = "Baller LE (Armored)", brand = "Gallivanter", category = "suvs" },
    [-32236122] = { model = "halftrack", name = "Half-track", brand = "Bravado", category = "military" },
    [509498602] = { model = "dinghy3", name = "Dinghy (Heist)", brand = "Nagasaki", category = "boats" },
    [-1523428744] = { model = "manchez", name = "Manchez", brand = "Maibatsu", category = "motorcycles" },
    [1348744438] = { model = "oracle", name = "Oracle", brand = "Übermacht", category = "sedans" },
    [788747387] = { model = "buzzard", name = "Buzzard Attack Chopper", brand = "Nagasaki", category = "helicopters" },
    [-1540373595] = { model = "vectre", name = "Vectre", brand = "Emperor", category = "sports" },
    [-1126264336] = { model = "minivan2", name = "Minivan Custom", brand = "Vapid", category = "vans" },
    [1938952078] = { model = "firetruk", name = "Fire Truck", brand = "MTL", category = "emergency" },
    [914654722] = { model = "mesa", name = "Mesa", brand = "Canis", category = "offroad" },
    [-713569950] = { model = "bus", name = "Bus", brand = "Brute", category = "service" },
    [1830407356] = { model = "peyote", name = "Peyote", brand = "Vapid", category = "sportsclassics" },
    [-998177792] = { model = "visione", name = "Visione", brand = "Grotti", category = "sports" },
    [-1566607184] = { model = "clique", name = "Clique", brand = "Vapid", category = "muscle" },
    [1692272545] = { model = "strikeforce", name = "B-11 Strikeforce", brand = "Unknown", category = "planes" },
    [655665811] = { model = "zeno", name = "Zeno", brand = "Överflöd", category = "super" },
    [-1934452204] = { model = "rapidgt", name = "Rapid GT", brand = "Dewbauchee", category = "sports" },
    [-477831899] = { model = "conada", name = "Conada", brand = "Buckingham", category = "helicopters" },
    [-1543762099] = { model = "gresley", name = "Gresley", brand = "Bravado", category = "suvs" },
    [1171614426] = { model = "ambulance", name = "Ambulance", brand = "Brute", category = "emergency" },
    [-2096690334] = { model = "impaler", name = "Impaler", brand = "Vapid", category = "muscle" },
    [682434785] = { model = "boxville5", name = "Armored Boxville", brand = "Brute", category = "vans" },
    [525509695] = { model = "moonbeam", name = "Moonbeam", brand = "Declasse", category = "vans" },
    [1741861769] = { model = "streiter", name = "Streiter", brand = "Benefactor", category = "sports" },
    [-1743316013] = { model = "burrito3", name = "Burrito", brand = "Declasse", category = "vans" },
    [1445631933] = { model = "tractor3", name = "Fieldmaster", brand = "Stanley", category = "utility" },
    [1881415402] = { model = "niobe", name = "Niobe", brand = "Ubermacht", category = "sports" },
    [-1507230520] = { model = "futo2", name = "Futo GTX", brand = "Karin", category = "sports" },
    [-420911112] = { model = "patriot2", name = "Patriot Stretch", brand = "Mammoth", category = "suvs" },
    [-979292575] = { model = "clique2", name = "Clique Wagon", brand = "Vapid", category = "muscle" },
    [475220373] = { model = "mixer2", name = "Mixer II", brand = "HVY", category = "industrial" },
    [-1943285540] = { model = "nightshade", name = "Nightshade", brand = "Imponte", category = "muscle" },
    [-1987130134] = { model = "boxville", name = "Boxville LSDWP", brand = "Brute", category = "vans" },
    [-1098802077] = { model = "rentalbus", name = "Rental Shuttle Bus", brand = "Brute", category = "service" },
    [-344943009] = { model = "blista", name = "Blista", brand = "Dinka", category = "compacts" },
    [-1693015116] = { model = "riot2", name = "RCV", brand = "Unknown", category = "emergency" },
    [630371791] = { model = "barracks3", name = "Barracks", brand = "HVY", category = "military" },
    [722226637] = { model = "gauntlet3", name = "Classic Gauntlet", brand = "Bravado", category = "muscle" },
    [330661258] = { model = "cogcabrio", name = "Cognoscenti Cabrio", brand = "Enus", category = "coupes" },
    [-663299102] = { model = "trophytruck2", name = "Desert Raid", brand = "Vapid", category = "offroad" },
    [-1523619738] = { model = "alphaz1", name = "Alpha-Z1", brand = "Buckingham", category = "planes" },
    [736672010] = { model = "dominator8", name = "Dominator GTT", brand = "Vapid", category = "muscle" },
    [1617472902] = { model = "fagaloa", name = "Fagaloa", brand = "Vulcar", category = "sportsclassics" },
    [-1453280962] = { model = "sanchez2", name = "Sanchez", brand = "Maibatsu", category = "motorcycles" },
    [-1216765807] = { model = "adder", name = "Adder", brand = "Truffade", category = "super", backengine = true },
    [569305213] = { model = "packer", name = "Packer", brand = "MTL", category = "commercial" },
    [-1374500452] = { model = "deathbike3", name = "Deathbike Nightmare", brand = "Deathbike", category = "motorcycles" },
    [1086534307] = { model = "manchez2", name = "Manchez Scout", brand = "Maibatsu", category = "motorcycles" },
    [-82626025] = { model = "savage", name = "Savage", brand = "Unknown", category = "helicopters" },
    [-1334453816] = { model = "trailers5", name = "Trailer (Christmas)", brand = "Unknown", category = "utility" },
    [-140902153] = { model = "vader", name = "Vader", brand = "Shitzu", category = "motorcycles" },
    [-1960756985] = { model = "formula2", name = "R88", brand = "Ocelot", category = "openwheel" },
    [-2045594037] = { model = "rebel2", name = "Rebel", brand = "Vapid", category = "offroad" },
    [92612664] = { model = "kalahari", name = "Kalahari", brand = "Canis", category = "offroad" },
    [-307958377] = { model = "blimp3", name = "Blimp", brand = "Unknown", category = "planes" },
    [-1995326987] = { model = "feltzer2", name = "Feltzer", brand = "Benefactor", category = "sports" },
    [2014313426] = { model = "vetir", name = "Vetir", brand = "Unknown", category = "military" },
    [2016857647] = { model = "futo", name = "Futo", brand = "Karin", category = "coupes" },
    [861409633] = { model = "jetmax", name = "Jetmax", brand = "Shitzu", category = "boats" },
    [972671128] = { model = "tampa", name = "Tampa", brand = "Declasse", category = "muscle" },
    [-210308634] = { model = "winky", name = "Winky", brand = "Vapid", category = "offroad" },
    [-1030275036] = { model = "seashark", name = "Seashark", brand = "Speedophile", category = "boats" },
    [37348240] = { model = "hotknife", name = "Hotknife", brand = "Vapid", category = "muscle" },
    [-1013450936] = { model = "buccaneer2", name = "Buccaneer Rider", brand = "Albany", category = "muscle" },
    [-1043459709] = { model = "marquis", name = "Marquis", brand = "Dinka", category = "boats" },
    [444994115] = { model = "imperator", name = "Imperator Arena", brand = "Vapid", category = "muscle" },
    [-122993285] = { model = "turismo3", name = "Turismo Omaggio", brand = "Grotti", category = "super", backengine = true },
    [-2007026063] = { model = "pbus", name = "Police Prison Bus", brand = "Vapid", category = "emergency" },
    [-1988428699] = { model = "terbyte", name = "Terrorbyte", brand = "Benefactor", category = "military" },
    [-986656474] = { model = "driftsentinel", name = "Drift Sentinel Classic", brand = "Ubermacht", category = "sports" },
    [16646064] = { model = "virgo3", name = "Virgo Classic", brand = "Dundreary", category = "muscle" },
    [1234311532] = { model = "gp1", name = "GP1", brand = "Progen", category = "super" },
    [-1756021720] = { model = "everon", name = "Everon", brand = "Karin", category = "offroad" },
    [-644710429] = { model = "cuban800", name = "Cuban 800", brand = "Western Company", category = "planes" },
    [2100457220] = { model = "panthere", name = "Panthere", brand = "Toundra", category = "sports" },
    [710198397] = { model = "supervolito", name = "SuperVolito", brand = "Buckingham", category = "helicopters" },
    [-305727417] = { model = "brickade", name = "Brickade", brand = "MTL", category = "service" },
    [-1089039904] = { model = "furoregt", name = "Furore GT", brand = "Lampadati", category = "sports" },
    [-1848994066] = { model = "neon", name = "Neon", brand = "Pfister", category = "sports" },
    [-956048545] = { model = "taxi", name = "Taxi", brand = "Vapid", category = "service" },
    [-986944621] = { model = "dominator3", name = "Dominator GTX", brand = "Vapid", category = "muscle" },
    [1030400667] = { model = "freight", name = "Freight Train", brand = "Unknown", category = "service" },
    [-5153954] = { model = "exemplar", name = "Exemplar", brand = "Dewbauchee", category = "coupes" },
    [1353720154] = { model = "flatbed", name = "Flatbed Truck", brand = "MTL", category = "industrial" },
    [-1106353882] = { model = "jester2", name = "Jester Racecar", brand = "Dinka", category = "sports" },
    [372621319] = { model = "vigero3", name = "Vigero ZX Convertible", brand = "Declasse", category = "muscle" },
    [1641462412] = { model = "tractor", name = "Tractor", brand = "Stanley", category = "utility" },
    [-32878452] = { model = "bombushka", name = "RM-10 Bombushka", brand = "Unknown", category = "planes" },
    [1353120668] = { model = "shinobi", name = "Shinobi", brand = "Nagasaki", category = "motorcycles" },
    [-823509173] = { model = "barracks", name = "Barracks", brand = "HVY", category = "military" },
    [1949211328] = { model = "frogger2", name = "Frogger", brand = "Maibatsu", category = "helicopters" },
    [1177543287] = { model = "dubsta", name = "Dubsta", brand = "Benefactor", category = "suvs" },
    [-947761570] = { model = "tiptruck2", name = "Tipper II", brand = "Brute", category = "industrial" },
    [1653666139] = { model = "pounder2", name = "Pounder Custom", brand = "MTL", category = "commercial" },
    [-1289178744] = { model = "faggio3", name = "Faggio Mod", brand = "Pegassi", category = "motorcycles" },
    [-746882698] = { model = "schwarzer", name = "Schwartzer", brand = "Benefactor", category = "sports" },
    [562680400] = { model = "apc", name = "APC Tank", brand = "HVY", category = "military" },
    [-664141241] = { model = "krieger", name = "Krieger", brand = "Benefactor", category = "super" },
    [989294410] = { model = "voltic2", name = "Rocket Voltic", brand = "Coil", category = "super" },
    [1455990255] = { model = "toreador", name = "Toreador", brand = "Pegassi", category = "sportsclassics" },
    [1162065741] = { model = "rumpo", name = "Rumpo", brand = "Bravado", category = "vans" },
    [1854776567] = { model = "issi7", name = "Issi Sport", brand = "Weeny", category = "compacts" },
    [-1477580979] = { model = "stanier", name = "Stanier", brand = "Vapid", category = "sedans" },
    [-1829436850] = { model = "novak", name = "Novak", brand = "Lampadati", category = "suvs" },
    [1229411063] = { model = "seasparrow2", name = "Sparrow", brand = "Unknown", category = "helicopters" },
    [1307736079] = { model = "castigator", name = "Castigator", brand = "Canis", category = "suvs" },
    [409049982] = { model = "kanjo", name = "Blista Kanjo", brand = "Dinka", category = "compacts" },
    [1886712733] = { model = "bulldozer", name = "Dozer", brand = "HVY", category = "industrial" },
    [1690421418] = { model = "driftnebula", name = "Nebula Turbo", brand = "Vulcar", category = "sportsclassics" },
    [-129283887] = { model = "phantom4", name = "Phantom (Christmas)", brand = "Vapid", category = "commercial" },
    [-1758137366] = { model = "penetrator", name = "Penetrator", brand = "Ocelot", category = "super" },
    [-2098947590] = { model = "stingergt", name = "Stinger GT", brand = "Grotti", category = "sportsclassics" },
    [167522317] = { model = "terminus", name = "Terminus", brand = "Canis", category = "offroad" },
    [-1757836725] = { model = "seven70", name = "Seven-70", brand = "Dewbauchee", category = "sports" },
    [340154634] = { model = "formula", name = "PR4", brand = "Progen", category = "openwheel" },
    [1748565021] = { model = "entity3", name = "Entity MT", brand = "Overflod", category = "super" },
    [1076201208] = { model = "r300", name = "300R", brand = "Annis", category = "sports" },
    [-1746576111] = { model = "mammatus", name = "Mammatus", brand = "JoBuilt", category = "planes" },
    [-1881846085] = { model = "trailersmall2", name = "Anti-Aircraft Trailer", brand = "Vom Feuer", category = "military" },
    [1951180813] = { model = "taco", name = "Taco Truck", brand = "Brute", category = "vans" },
    [-1858654120] = { model = "zr350", name = "ZR350", brand = "Annis", category = "sports" },
    [-1009268949] = { model = "zombiea", name = "Zombie Bobber", brand = "Western", category = "motorcycles" },
    [223258115] = { model = "sabregt2", name = "Sabre GT Turbo Custom", brand = "Declasse", category = "muscle" },
    [1034187331] = { model = "nero", name = "Nero", brand = "Truffade", category = "super" },
    [-2052737935] = { model = "mule3", name = "Mule", brand = "Maibatsu", category = "vans" },
    [408970549] = { model = "avenger2", name = "Avenger", brand = "Mammoth", category = "planes" },
    [833469436] = { model = "slamvan2", name = "Lost Slam Van", brand = "Vapid", category = "muscle" },
    [1104234922] = { model = "sentinel3", name = "Sentinel Classic", brand = "Übermacht", category = "coupes" },
    [-1532697517] = { model = "riata", name = "Riata", brand = "Vapid", category = "offroad" },
    [941800958] = { model = "casco", name = "Casco", brand = "Lampadati", category = "sportsclassics" },
    [-1233807380] = { model = "tribike2", name = "Endurex Race Bike", brand = "Bike", category = "cycles" },
    [1581459400] = { model = "windsor", name = "Windsor", brand = "Enus", category = "coupes" },
    [-1297672541] = { model = "jester", name = "Jester", brand = "Dinka", category = "sports" },
    [1878062887] = { model = "baller3", name = "Baller LE", brand = "Gallivanter", category = "suvs" },
    [-1674384553] = { model = "police5", name = "Stanier LE Cruiser", brand = "Vapid", category = "emergency" },
    [159274291] = { model = "ardent", name = "Ardent", brand = "Ocelot", category = "sportsclassics" },
    [-1237253773] = { model = "dubsta3", name = "Dubsta 6x6", brand = "Annis", category = "offroad" },
    [1934384720] = { model = "gauntlet4", name = "Gauntlet Hellfire", brand = "Bravado", category = "muscle" },
    [838982985] = { model = "z190", name = "190Z", brand = "Karin", category = "sportsclassics" },
    [-619930876] = { model = "buffalo4", name = "Buffalo STX", brand = "Bravado", category = "muscle" },
    [1093792632] = { model = "nero2", name = "Nero Custom", brand = "Truffade", category = "super" },
    [1036591958] = { model = "nokota", name = "P-45 Nokota", brand = "Unknown", category = "planes" },
    [2136773105] = { model = "rocoto", name = "Rocoto", brand = "Obey", category = "suvs" },
    [-670086588] = { model = "patriot3", name = "Patriot Military", brand = "Mil-Spec", category = "suvs" },
    [-1214505995] = { model = "shamal", name = "Shamal", brand = "Buckingham", category = "planes" },
    [-1193103848] = { model = "zion2", name = "Zion Cabrio", brand = "Übermacht", category = "coupes" },
    [-2140431165] = { model = "bagger", name = "Bagger", brand = "WMC", category = "motorcycles" },
    [662793086] = { model = "iwagen", name = "Obey", brand = "I-Wagen", category = "sedans" },
    [1968807591] = { model = "pizzaboy", name = "Pizza Boy", brand = "Pegassi", category = "motorcycles" },
    [-845979911] = { model = "ripley", name = "Ripley", brand = "HVY", category = "utility" },
    [-1779120616] = { model = "policeold2", name = "Police Roadcruiser", brand = "Albany", category = "emergency" },
    [1717532765] = { model = "manana2", name = "Manana Custom", brand = "Albany", category = "muscle" },
    [-1590337689] = { model = "blazer5", name = "Blazer Aqua", brand = "Nagasaki", category = "offroad" },
    [-1576586413] = { model = "brickade2", name = "Brickade 6x6", brand = "MTL", category = "service" },
    [1203490606] = { model = "xls", name = "XLS", brand = "Benefactor", category = "suvs" },
    [-599568815] = { model = "sadler", name = "Sadler", brand = "Vapid", category = "utility" },
    [989381445] = { model = "sandking2", name = "Sandking SWB", brand = "Vapid", category = "offroad" },
    [-1066334226] = { model = "submersible2", name = "Kraken", brand = "Kraken Subs", category = "boats" },
    [1824333165] = { model = "besra", name = "Besra", brand = "Western Company", category = "planes" },
    [-757735410] = { model = "fcr2", name = "FCR 1000 Custom", brand = "Pegassi", category = "motorcycles" },
    [1871995513] = { model = "yosemite", name = "Yosemite", brand = "Declasse", category = "muscle" },
    [-1361687965] = { model = "chino2", name = "Chino Luxe", brand = "Vapid", category = "muscle" },
    [-34623805] = { model = "policeb", name = "Police Bike", brand = "Vapid", category = "emergency" },
    [1887331236] = { model = "tropos", name = "Tropos Rallye", brand = "Lampadati", category = "sports" },
    [-591610296] = { model = "f620", name = "F620", brand = "Ocelot", category = "coupes" },
    [-1930048799] = { model = "windsor2", name = "Windsor Drop", brand = "Enus", category = "coupes" },
    [-1582061455] = { model = "jester4", name = "Jester RR", brand = "Dinka", category = "sports" },
    [-48031959] = { model = "blazer2", name = "Blazer Lifeguard", brand = "Nagasaki", category = "offroad" },
    [-1386191424] = { model = "pyro", name = "Pyro", brand = "Buckingham", category = "planes" },
    [-1435527158] = { model = "khanjali", name = "TM-02 Khanjali Tank", brand = "Unknown", category = "military" },
    [-842765535] = { model = "boxville6", name = "Boxville (LSDS)", brand = "Brute", category = "vans" },
    [-461850249] = { model = "tahoma", name = "Tahoma Coupe", brand = "Declasse", category = "coupes" },
    [633712403] = { model = "banshee2", name = "Banshee 900R", brand = "Bravado", category = "super" },
    [101905590] = { model = "trophytruck", name = "Trophy Truck", brand = "Vapid", category = "offroad" },
    [-768044142] = { model = "dorado", name = "Dorado", brand = "Bravado", category = "suvs" },
    [-777172681] = { model = "omnis", name = "Omnis", brand = "Wow", category = "sports" },
    [873639469] = { model = "sentinel2", name = "Sentinel XS", brand = "Übermacht", category = "coupes" },
    [640818791] = { model = "lectro", name = "Lectro", brand = "Principe", category = "motorcycles" },
    [-400295096] = { model = "tribike3", name = "Tri-Cycles Race Bike", brand = "Bike", category = "cycles" },
    [-131348178] = { model = "everon2", name = "Everon Hotring", brand = "Karin", category = "sports" },
    [908897389] = { model = "toro2", name = "Toro Yacht", brand = "Lampadati", category = "boats" },
    [2053223216] = { model = "benson", name = "Benson", brand = "Vapid", category = "commercial" },
    [-311022263] = { model = "seashark3", name = "Seashark Yacht", brand = "Speedophile", category = "boats" },
    [1123216662] = { model = "superd", name = "Super Diamond", brand = "Enus", category = "sedans" },
    [-1289722222] = { model = "ingot", name = "Ingot", brand = "Vulcar", category = "sedans" },
    [-505223465] = { model = "omnisegt", name = "Omnis e-GT", brand = "Obey", category = "sports" },
    [-1728685474] = { model = "coquette4", name = "Coquette D10", brand = "Invetero", category = "sports" },
    [-2124201592] = { model = "manana", name = "Manana", brand = "Albany", category = "muscle" },
    [-405626514] = { model = "shotaro", name = "Shotaro", brand = "Nagasaki", category = "motorcycles" },
    [-16948145] = { model = "bison", name = "Bison", brand = "Bravado", category = "vans" },
    [-754687673] = { model = "corsita", name = "Corsita", brand = "Lampadati", category = "sports" },
    [1802742206] = { model = "youga3", name = "Youga Classic 4x4", brand = "Bravado", category = "vans" },
    [516990260] = { model = "utillitruck", name = "Utility Truck (Cherry Picker)", brand = "Brute", category = "utility" },
    [-1797613329] = { model = "tornado5", name = "Tornado Custom", brand = "Declasse", category = "sportsclassics" },
    [1549126457] = { model = "brioso", name = "Brioso R/A", brand = "Grotti", category = "compacts" },
    [-54332285] = { model = "freecrawler", name = "Freecrawler", brand = "Canis", category = "offroad" },
    [-1035489563] = { model = "surfer3", name = "Surfer Custom", brand = "BF", category = "vans" },
    [610429990] = { model = "coureur", name = "La Coureuse", brand = "Penaud", category = "sports" },
    [-465825307] = { model = "fr36", name = "FR36", brand = "Fathom", category = "coupes" },
    [-1045911276] = { model = "slamtruck", name = "Slam Truck", brand = "Vapid", category = "utility" },
    [-1651067813] = { model = "radi", name = "Radius", brand = "Vapid", category = "suvs" },
    [-1622444098] = { model = "voltic", name = "Voltic", brand = "Coil", category = "super" },
    [887537515] = { model = "utillitruck2", name = "Utility Truck (Van)", brand = "Brute", category = "utility" },
    [-909201658] = { model = "pcj", name = "PCJ-600", brand = "Shitzu", category = "motorcycles" },
    [686471183] = { model = "drafter", name = "8F Drafter", brand = "Obey", category = "sports" },
    [-1403128555] = { model = "zentorno", name = "Zentorno", brand = "Pegassi", category = "super", backengine = true },
    [1046206681] = { model = "michelli", name = "Michelli GT", brand = "Lampadati", category = "sportsclassics" },
    [-1137532101] = { model = "fq2", name = "FQ2", brand = "Fathom", category = "suvs" },
    [1737773231] = { model = "rapidgt2", name = "Rapid GT Convertible", brand = "Dewbauchee", category = "sports" },
    [258105345] = { model = "driftcypher", name = "Drift Cypher", brand = "Ubermacht", category = "sports" },
    [1489967196] = { model = "schafter4", name = "Schafter LWB", brand = "Benefactor", category = "sports" },
    [80636076] = { model = "dominator", name = "Dominator", brand = "Vapid", category = "muscle" },
    [-142942670] = { model = "massacro", name = "Massacro", brand = "Dewbauchee", category = "sports" },
    [-310465116] = { model = "minivan", name = "Minivan", brand = "Vapid", category = "vans" },
    [-570033273] = { model = "zombieb", name = "Zombie Chopper", brand = "Western", category = "motorcycles" },
    [1663218586] = { model = "t20", name = "T20", brand = "Progen", category = "super", backengine = true },
    [-410205223] = { model = "revolter", name = "Revolter", brand = "Übermacht", category = "sports" },
    [-769147461] = { model = "caddy3", name = "Caddy (Golf)", brand = "Nagasaki", category = "utility" },
    [444583674] = { model = "handler", name = "Dock Handler", brand = "HVY", category = "industrial" },
    [1862507111] = { model = "zion3", name = "Zion Classic", brand = "Übermacht", category = "sportsclassics" },
    [471034616] = { model = "tvtrailer2", name = "Trailer (TV)", brand = "Unknown", category = "utility" },
    [-1700801569] = { model = "scrap", name = "Scrap Truck", brand = "Vapid", category = "utility" },
    [-178442374] = { model = "impaler6", name = "Impaler LX", brand = "Declasse", category = "muscle" },
    [482197771] = { model = "lynx", name = "Lynx", brand = "Ocelot", category = "sports" },
    [-1008861746] = { model = "tailgater", name = "Tailgater", brand = "Obey", category = "sedans" },
    [886934177] = { model = "intruder", name = "Intruder", brand = "Karin", category = "sedans" },
    [1031562256] = { model = "tezeract", name = "Tezeract", brand = "Pegassi", category = "super" },
    [296357396] = { model = "gburrito2", name = "Burrito Custom", brand = "Declasse", category = "vans" },
    [2006918058] = { model = "cavalcade", name = "Cavalcade", brand = "Albany", category = "suvs" },
    [142944341] = { model = "baller2", name = "Baller II", brand = "Gallivanter", category = "suvs" },
    [-365873403] = { model = "alkonost", name = "RO-86 Alkonost", brand = "Unknown", category = "planes" },
    [469291905] = { model = "lguard", name = "Lifeguard", brand = "Declasse", category = "emergency" },
    [-1566741232] = { model = "feltzer3", name = "Stirling GT", brand = "Benefactor", category = "sportsclassics" },
    [384071873] = { model = "surano", name = "Surano", brand = "Benefactor", category = "sports" },
    [1074326203] = { model = "barracks2", name = "Barracks Semi", brand = "HVY", category = "military" },
    [-1958428933] = { model = "coquette5", name = "Coquette D1", brand = "Invetero", category = "sports" },
    [-391595372] = { model = "viseris", name = "Viseris", brand = "Lampadati", category = "sportsclassics" },
    [-2122646867] = { model = "gauntlet5", name = "Gauntlet Classic Custom", brand = "Bravado", category = "muscle" },
    [1981688531] = { model = "titan", name = "Titan", brand = "Unknown", category = "planes" },
    [906642318] = { model = "cog55", name = "Cognoscenti 55", brand = "Enus", category = "sedans" },
    [-2079788230] = { model = "gt500", name = "GT500", brand = "Grotti", category = "sportsclassics" },
    [743478836] = { model = "sovereign", name = "Sovereign", brand = "WMC", category = "motorcycles" },
    [-150975354] = { model = "blimp", name = "Atomic Blimp", brand = "Unknown", category = "planes" },
    [1489874736] = { model = "thruster", name = "Thruster", brand = "Mammoth", category = "military" },
    [-2095439403] = { model = "phoenix", name = "Phoenix", brand = "Imponte", category = "muscle" },
    [1416471345] = { model = "previon", name = "Previon", brand = "Karin", category = "coupes" },
    [-2103821244] = { model = "rallytruck", name = "Dune", brand = "MTL", category = "service" },
    [234062309] = { model = "reaper", name = "Reaper", brand = "Pegassi", category = "super" },
    [1304459735] = { model = "growler", name = "Growler", brand = "Pfister", category = "sports" },
    [-498054846] = { model = "virgo", name = "Virgo", brand = "Albany", category = "muscle" },
    [-1649536104] = { model = "phantom2", name = "Phantom Wedge", brand = "Jobuilt", category = "commercial" },
    [-1323100960] = { model = "towtruck", name = "Tow Truck (Large)", brand = "Vapid", category = "utility" },
    [-688189648] = { model = "dominator4", name = "Dominator Arena", brand = "Vapid", category = "muscle" },
    [1565978651] = { model = "molotok", name = "V-65 Molotok", brand = "Unknown", category = "planes" },
    [2068293287] = { model = "lurcher", name = "Lurcher", brand = "Bravado", category = "muscle" },
    [1336872304] = { model = "kosatka", name = "Kosatka", brand = "Rune", category = "military" },
    [1039032026] = { model = "blista2", name = "Blista Compact", brand = "Dinka", category = "compacts" },
    [2038480341] = { model = "euros", name = "Euros", brand = "Annis", category = "sports" },
    [-255678177] = { model = "hakuchou2", name = "Hakuchou Drag", brand = "Shitzu", category = "motorcycles" },
    [-394074634] = { model = "dubsta2", name = "Dubsta Luxury", brand = "Benefactor", category = "suvs" },
    [-1700874274] = { model = "starling", name = "LF-22 Starling", brand = "Unknown", category = "planes" },
    [1078682497] = { model = "pigalle", name = "Pigalle", brand = "Lampadati", category = "sportsclassics" },
    [-1842748181] = { model = "faggio", name = "Faggio Sport", brand = "Pegassi", category = "motorcycles" },
    [486987393] = { model = "huntley", name = "Huntley S", brand = "Enus", category = "suvs" },
    [-212993243] = { model = "barrage", name = "Barrage", brand = "HVY", category = "military" },
    [941494461] = { model = "ruiner2", name = "Ruiner 2000", brand = "Imponte", category = "muscle" },
    [600450546] = { model = "hustler", name = "Hustler", brand = "Vapid", category = "muscle" },
    [723973206] = { model = "dukes", name = "Dukes", brand = "Imponte", category = "muscle" },
    [1532171089] = { model = "deity", name = "Deity", brand = "Enus", category = "sedans" },
    [1912215274] = { model = "police3", name = "Police Interceptor", brand = "Vapid", category = "emergency" },
    [-975345305] = { model = "rogue", name = "Rogue", brand = "Western Company", category = "planes" },
    [-143587026] = { model = "driftvorschlag", name = "Vorschlaghammer", brand = "Pfister", category = "sports" },
    [-376434238] = { model = "tyrant", name = "Tyrant", brand = "Överflöd", category = "super" },
    [-1007528109] = { model = "howard", name = "Howard NX-25", brand = "Unknown", category = "planes" },
    [1249425552] = { model = "polimpaler5", name = "Impaler SZ Cruiser", brand = "Declasse", category = "emergency" },
    [177270108] = { model = "phantom3", name = "Phantom Custom", brand = "Jobuilt", category = "commercial" },
    [349315417] = { model = "gauntlet2", name = "Redwood Gauntlet", brand = "Bravado", category = "muscle" },
    [-276744698] = { model = "patrolboat", name = "Kurtz 31 Patrol Boat", brand = "Unknown", category = "boats" },
    [15219735] = { model = "hermes", name = "Hermes", brand = "Albany", category = "muscle" },
    [-38879449] = { model = "aleutian", name = "Aleutian", brand = "Vapid", category = "suvs" },
    [-223461503] = { model = "pipistrello", name = "Pipistrello", brand = "Overflod", category = "sports" },
    [-42959138] = { model = "hunter", name = "FH-1 Hunter", brand = "Unknown", category = "helicopters" },
    [11251904] = { model = "carbonrs", name = "Carbon RS", brand = "Nagasaki", category = "motorcycles" },
    [-941272559] = { model = "locust", name = "Locust", brand = "Ocelot", category = "sports" },
    [775514032] = { model = "sm722", name = "SM722", brand = "Benefactor", category = "sports" },
    [-613725916] = { model = "blimp2", name = "Xero Blimp", brand = "Unknown", category = "planes" },
    [-433375717] = { model = "monroe", name = "Monroe", brand = "Pegassi", category = "sportsclassics" },
    [1693751655] = { model = "yosemite2", name = "Yosemite Drift", brand = "Declasse", category = "muscle" },
    [461465043] = { model = "jubilee", name = "Jubilee", brand = "Enus", category = "sedans" },
    [-1311154784] = { model = "cheetah", name = "Cheetah", brand = "Grotti", category = "super" },
    [-2120700196] = { model = "entity2", name = "Entity XXR", brand = "Överflöd", category = "super" },
    [-634879114] = { model = "nemesis", name = "Nemesis", brand = "Principe", category = "motorcycles" },
    [1044193113] = { model = "thrax", name = "Thrax", brand = "Truffade", category = "super" },
    [1561920505] = { model = "comet4", name = "Comet Safari", brand = "Pfister", category = "sports", backengine = true },
    [-1726022652] = { model = "comet6", name = "Comet S2", brand = "Pfister", category = "sports", backengine = true },
    [464687292] = { model = "tornado", name = "Tornado", brand = "Declasse", category = "sportsclassics" },
    [-1386336041] = { model = "powersurge", name = "Powersurge", brand = "Western", category = "motorcycles" },
    [-1973172295] = { model = "police4", name = "Unmarked Cruiser", brand = "Vapid", category = "emergency" },
    [86520421] = { model = "bf400", name = "BF400", brand = "Nagasaki", category = "motorcycles" },
    [-1804415708] = { model = "peyote2", name = "Peyote Gasser", brand = "Vapid", category = "sportsclassics" },
    [-2076478498] = { model = "tractor2", name = "Fieldmaster", brand = "Stanley", category = "utility" },
    [-392675425] = { model = "seabreeze", name = "Seabreeze", brand = "Western Company", category = "planes" },
    [1987142870] = { model = "osiris", name = "Osiris", brand = "Pegassi", category = "super", backengine = true },
    [872704284] = { model = "sultan2", name = "Sultan Custom", brand = "Karin", category = "sports" },
    [-1029730482] = { model = "cavalcade3", name = "Cavalcade XL", brand = "Albany", category = "suvs" },
    [1426219628] = { model = "fmj", name = "FMJ", brand = "Vapid", category = "super" },
    [837858166] = { model = "annihilator", name = "Annihilator", brand = "Western Company", category = "helicopters" },
    [2072687711] = { model = "carbonizzare", name = "Carbonizzare", brand = "Grotti", category = "sports" },
    [-261346873] = { model = "granger2", name = "Granger 3600LX", brand = "Declasse", category = "suvs" },
    [-1706603682] = { model = "avisa", name = "Avisa", brand = "Kraken Subs", category = "boats" },
    [1682114128] = { model = "dilettante2", name = "Dilettante Patrol", brand = "Karin", category = "compacts" },
    [-618617997] = { model = "wolfsbane", name = "Wolfsbane", brand = "Western", category = "motorcycles" },
    [767087018] = { model = "alpha", name = "Alpha", brand = "Albany", category = "sports" },
    [1790834270] = { model = "diablous2", name = "Diablous Custom", brand = "Principe", category = "motorcycles" },
    [-1620126302] = { model = "neo", name = "Neo", brand = "Vysser", category = "sports" },
    [-624529134] = { model = "jackal", name = "Jackal", brand = "Ocelot", category = "coupes" },
    [-789894171] = { model = "cavalcade2", name = "Cavalcade II", brand = "Albany", category = "suvs" },
    [699456151] = { model = "surfer", name = "Surfer", brand = "BF", category = "vans" },
    [-1809822327] = { model = "asea", name = "Asea", brand = "Declasse", category = "sedans" },
    [-1177863319] = { model = "issi2", name = "Issi", brand = "Weeny", category = "compacts" },
    [1058115860] = { model = "jet", name = "Jet", brand = "Unknown", category = "planes" },
    [-2107990196] = { model = "guardian", name = "Guardian", brand = "Vapid", category = "industrial" },
    [1518533038] = { model = "hauler", name = "Hauler", brand = "Jobuilt", category = "commercial" },
    [1051415893] = { model = "jb700", name = "JB 700", brand = "Dewbauchee", category = "sportsclassics" },
    [1121330119] = { model = "envisage", name = "Envisage", brand = "Bollokan", category = "sportsclassics" },
    [-511601230] = { model = "oracle2", name = "Oracle XS", brand = "Übermacht", category = "coupes" },
    [-863358884] = { model = "baller8", name = "Baller ST-D", brand = "Gallivanter", category = "suvs" },
    [1753414259] = { model = "enduro", name = "Enduro", brand = "Dinka", category = "motorcycles" },
    [-89291282] = { model = "felon2", name = "Felon GT", brand = "Lampadati", category = "coupes" },
    [-1130810103] = { model = "dilettante", name = "Dilettante", brand = "Karin", category = "compacts" },
    [-901163259] = { model = "dodo", name = "Dodo", brand = "Mammoth", category = "planes" },
    [298565713] = { model = "verus", name = "Verus", brand = "Dinka", category = "offroad" },
    [1922257928] = { model = "sheriff2", name = "Sheriff Cruiser", brand = "Vapid", category = "emergency" },
    [-1349095620] = { model = "caracara2", name = "Caracara 4x4", brand = "Vapid", category = "offroad" },
    [1102544804] = { model = "verlierer2", name = "Verlierer", brand = "Bravado", category = "sports" },
    [1483171323] = { model = "deluxo", name = "Deluxo", brand = "Imponte", category = "sportsclassics" },
    [745926877] = { model = "buzzard2", name = "Buzzard", brand = "Nagasaki", category = "helicopters" },
    [-1356880839] = { model = "sentinel4", name = "Sentinel Classic Widebody", brand = "Übermacht", category = "sports" },
    [-1984275979] = { model = "havok", name = "Havok", brand = "Nagasaki", category = "helicopters" },
    [1755697647] = { model = "cypher", name = "Cypher", brand = "Übermacht", category = "sports" },
    [1475773103] = { model = "rumpo3", name = "Rumpo Custom", brand = "Bravado", category = "vans" },
    [1644055914] = { model = "weevil", name = "Weevil", brand = "BF", category = "compacts" },
    [-1372798934] = { model = "vivanite", name = "Vivanite", brand = "Karin", category = "suvs" },
    [1377217886] = { model = "remus", name = "Remus", brand = "Annis", category = "sports" },
    [2031587082] = { model = "retinue2", name = "Retinue MKII", brand = "Vapid", category = "sportsclassics" },
    [-304802106] = { model = "buffalo", name = "Buffalo", brand = "Bravado", category = "sports" },
    [-1812949672] = { model = "deathbike2", name = "Deathbike Future Shock", brand = "Deathbike", category = "motorcycles" },
    [-1405937764] = { model = "infernus2", name = "Infernus Classic", brand = "Pegassi", category = "sportsclassics", backengine = true },
    [-1660945322] = { model = "mamba", name = "Mamba", brand = "Declasse", category = "sportsclassics" },
    [-589178377] = { model = "ratloader2", name = "Ratloader", brand = "Ratloader2", category = "muscle" },
    [-1259134696] = { model = "flashgt", name = "Flash GT", brand = "Vapid", category = "sports" },
    [970385471] = { model = "hydra", name = "Hydra", brand = "Mammoth", category = "planes" },
    [1923400478] = { model = "stalion", name = "Stallion", brand = "Declasse", category = "muscle" },
    [-349601129] = { model = "bifta", name = "Bifta", brand = "Annis", category = "offroad" },
    [1118611807] = { model = "asbo", name = "Asbo", brand = "Maxwell", category = "compacts" },
    [75131841] = { model = "glendale", name = "Glendale", brand = "Benefactor", category = "sedans" },
    [931280609] = { model = "issi3", name = "Issi Classic", brand = "Weeny", category = "compacts" },
    [-1705304628] = { model = "rubble", name = "Rubble", brand = "Jobuilt", category = "industrial" },
    [1070967343] = { model = "toro", name = "Toro", brand = "Lampadati", category = "boats" },
    [-682108547] = { model = "zorrusso", name = "Zorrusso", brand = "Pegassi", category = "super" },
    [1783355638] = { model = "mower", name = "Lawn Mower", brand = "Jacksheepe", category = "utility" },
    [65402552] = { model = "youga", name = "Youga", brand = "Bravado", category = "vans" },
    [-331467772] = { model = "italigto", name = "Itali GTO", brand = "Progen", category = "sports" },
    [744705981] = { model = "frogger", name = "Frogger", brand = "Maibatsu", category = "helicopters" },
    [-44799464] = { model = "speedo5", name = "Speedo Custom", brand = "Vapid", category = "vans" },
    [1011753235] = { model = "coquette2", name = "Coquette Classic", brand = "Invetero", category = "sportsclassics" },
    [2132890591] = { model = "utillitruck3", name = "Utility Truck (Contender)", brand = "Vapid", category = "utility" },
    [-834353991] = { model = "komoda", name = "Komoda", brand = "Lampadati", category = "sports" },
    [-1661854193] = { model = "dune", name = "Dune Buggy", brand = "Annis", category = "offroad" },
    [-913589546] = { model = "glendale2", name = "Glendale Custom", brand = "Benefactor", category = "sedans" },
    [1637620610] = { model = "imperator2", name = "imperator Future Shock", brand = "Vapid", category = "muscle" },
    [1352136073] = { model = "sc1", name = "SC1", brand = "Übermacht", category = "super" },
    [-1758379524] = { model = "vigero2", name = "Vigero ZX", brand = "Declasse", category = "muscle" },
    [1917016601] = { model = "trash", name = "Trashmaster", brand = "JoBuilt", category = "service" },
    [970598228] = { model = "sultan", name = "Sultan", brand = "Karin", category = "sports" },
    [1645267888] = { model = "rancherxl", name = "Rancher XL", brand = "Declasse", category = "offroad" },
    [1033245328] = { model = "dinghy", name = "Dinghy 2-Seater", brand = "Nagasaki", category = "boats" },
    [987469656] = { model = "sugoi", name = "Sugoi", brand = "Dinka", category = "sports" },
    [-994371320] = { model = "weevil2", name = "Weevil Custom", brand = "BF", category = "muscle" },
    [1909141499] = { model = "fugitive", name = "Fugitive", brand = "Cheval", category = "sedans" },
    [884483972] = { model = "oppressor", name = "Oppressor", brand = "Pegassi", category = "motorcycles" },
    [1941029835] = { model = "tourbus", name = "Tour Bus", brand = "Brute", category = "service" },
    [-391594584] = { model = "felon", name = "Felon", brand = "Lampadati", category = "coupes" },
    [-1255698084] = { model = "trash2", name = "Trashmaster", brand = "JoBuilt", category = "service" },
    [-1150599089] = { model = "primo", name = "Primo", brand = "Albany", category = "sedans" },
    [1119641113] = { model = "slamvan3", name = "Slam Van Custom", brand = "Vapid", category = "muscle" },
    [1672195559] = { model = "akuma", name = "Akuma", brand = "Dinka", category = "motorcycles" },
    [1836027715] = { model = "thrust", name = "Thrust", brand = "Dinka", category = "motorcycles" },
    [-1903012613] = { model = "asterope", name = "Asterope", brand = "Karin", category = "sedans" },
    [-882629065] = { model = "nebula", name = "Nebula", brand = "Vulcar", category = "sportsclassics" },
    [231083307] = { model = "speeder", name = "Speeder", brand = "Pegassi", category = "boats" },
    [-295689028] = { model = "sultanrs", name = "Sultan RS", brand = "Karin", category = "sports" },
    [-1240172147] = { model = "vorschlaghammer", name = "Vorschlaghammer", brand = "Pfister", category = "sports" },
    [1723137093] = { model = "stratum", name = "Stratum", brand = "Zirconium", category = "sedans" },
    [-591651781] = { model = "blista3", name = "Blista Go Go Monkey", brand = "Dinka", category = "compacts" },
    [819197656] = { model = "sheava", name = "ETR1", brand = "Emperor", category = "super" },
    [1737348074] = { model = "polgreenwood", name = "Greenwood Cruiser", brand = "Bravado", category = "emergency" },
    [-1358197432] = { model = "tigon", name = "Tigon", brand = "Lampadati", category = "super" },
    [-1134706562] = { model = "taipan", name = "Taipan", brand = "Cheval", category = "super" },
    [-2022483795] = { model = "comet3", name = "Comet Retro Custom", brand = "Pfister", category = "sports", backengine = true },
    [1269098716] = { model = "landstalker", name = "Landstalker", brand = "Dundreary", category = "suvs" },
    [-1050465301] = { model = "mule2", name = "Mule", brand = "Maibatsu", category = "vans" },
    [-899509638] = { model = "virgo2", name = "Virgo Custom Classic", brand = "Dundreary", category = "muscle" },
    [-282946103] = { model = "suntrap", name = "Suntrap", brand = "Shitzu", category = "boats" },
    [1392481335] = { model = "cyclone", name = "Cyclone", brand = "Coil", category = "super" },
    [1274868363] = { model = "bestiagts", name = "Bestia GTS", brand = "Grotti", category = "sports" },
    [-214906006] = { model = "jester3", name = "Jester Classic", brand = "Dinka", category = "sports" },
    [1873600305] = { model = "ratbike", name = "Rat Bike", brand = "Western", category = "motorcycles" },
    [1909189272] = { model = "gb200", name = "GB 200", brand = "Vapid", category = "sports" },
    [15214558] = { model = "brioso3", name = "Brioso 300 Widebody", brand = "Grotti", category = "compacts" },
    [-1670998136] = { model = "double", name = "Double-T", brand = "Dinka", category = "motorcycles" },
    [321186144] = { model = "stafford", name = "Stafford", brand = "Enus", category = "sedans" },
    [-1189015600] = { model = "sandking", name = "Sandking XL", brand = "Vapid", category = "offroad" },
    [-294678663] = { model = "postlude", name = "Postlude", brand = "Dinka", category = "coupes" },
    [1341619767] = { model = "vestra", name = "Vestra", brand = "Buckingham", category = "planes" },
    [-1168952148] = { model = "toros", name = "Toros", brand = "Pegassi", category = "suvs" },
    [-915234475] = { model = "champion", name = "Champion", brand = "Dewbauchee", category = "coupes" },
    [741090084] = { model = "gargoyle", name = "Gargoyle", brand = "Western", category = "motorcycles" },
    [-893984159] = { model = "tenf", name = "10F", brand = "Obey", category = "sports" },
    [1127131465] = { model = "fbi", name = "FIB Buffalo", brand = "Bravado", category = "emergency" },
    [-14495224] = { model = "regina", name = "Regina", brand = "Dundreary", category = "sedans" },
    [-1244461404] = { model = "tailgater2", name = "Tailgater S", brand = "Obey", category = "sedans" },
    [-362150785] = { model = "hellion", name = "Hellion", brand = "Annis", category = "offroad" },
    [-1627077503] = { model = "journey2", name = "Journey II", brand = "Zirconium", category = "vans" },
    [-227741703] = { model = "ruiner", name = "Ruiner", brand = "Imponte", category = "muscle" },
    [-1281684762] = { model = "lazer", name = "P-996 Lazer", brand = "JoBuilt", category = "planes" },
    [-2040426790] = { model = "primo2", name = "Primo Custom", brand = "Albany", category = "sedans" },
    [-631322662] = { model = "penumbra2", name = "Penumbra FF", brand = "Maibatsu", category = "sports" },
    [418536135] = { model = "infernus", name = "Infernus", brand = "Pegassi", category = "super" },
    [-324618589] = { model = "s80", name = "S80RR", brand = "Annis", category = "super" },
    [-1267543371] = { model = "ellie", name = "Ellie", brand = "Vapid", category = "muscle" },
    [1239571361] = { model = "issi6", name = "Issi Nightmare", brand = "Weeny", category = "compacts" },
    [349605904] = { model = "chino", name = "Chino", brand = "Vapid", category = "muscle" },
    [426742808] = { model = "dominator7", name = "Dominator ASP", brand = "Vapid", category = "muscle" },
    [1447690049] = { model = "stingertt", name = "Itali GTO Stinger TT", brand = "Maibatsu", category = "sports" },
    [-401643538] = { model = "stalion2", name = "Stallion Burgershot", brand = "Declasse", category = "muscle" },
    [1279262537] = { model = "deviant", name = "Deviant", brand = "Schyster", category = "muscle" },
    [-884690486] = { model = "docktug", name = "Docktug", brand = "HVY", category = "utility" },
    [-602287871] = { model = "btype3", name = "Roosevelt Valor", brand = "Albany", category = "sportsclassics" },
    [996383885] = { model = "boor", name = "Boor", brand = "Karin", category = "compacts" },
    [-339587598] = { model = "swift", name = "Swift", brand = "Buckingham", category = "helicopters" },
    [1545842587] = { model = "stinger", name = "Stinger", brand = "Grotti", category = "sportsclassics" },
    [1504306544] = { model = "torero", name = "Torero", brand = "Pegassi", category = "sportsclassics" },
    [661493923] = { model = "comet5", name = "Comet SR", brand = "Pfister", category = "sports", backengine = true },
    [-1045541610] = { model = "comet2", name = "Comet", brand = "Pfister", category = "sports", backengine = true },
    [-2039755226] = { model = "faction3", name = "Faction Custom Donk", brand = "Willard", category = "muscle" },
    [-1249788006] = { model = "eudora", name = "Eudora", brand = "Willard", category = "sedans" },
    [1032823388] = { model = "ninef", name = "9F", brand = "Obey", category = "sports" },
    [1939284556] = { model = "vagner", name = "Vagner", brand = "Dewbauchee", category = "super" },
    [1126868326] = { model = "bfinjection", name = "Bf Injection", brand = "Annis", category = "offroad" },
    [-186537451] = { model = "scorcher", name = "Scorcher", brand = "Bike", category = "cycles" },
    [-1671539132] = { model = "supervolito2", name = "SuperVolito Carbon", brand = "Buckingham", category = "helicopters" },
    [-1444114309] = { model = "ignus", name = "Ignus", brand = "Pegassi", category = "super" },
    [917809321] = { model = "xa21", name = "XA-21", brand = "Ocelot", category = "super" },
    [544021352] = { model = "khamelion", name = "Khamelion", brand = "Hijak", category = "sports" },
    [-1536924937] = { model = "policeold1", name = "Police Rancher", brand = "Declasse", category = "emergency" },
    [40817712] = { model = "greenwood", name = "Greenwood", brand = "Bravado", category = "muscle" },
    [-1660661558] = { model = "maverick", name = "Maverick", brand = "Buckingham", category = "helicopters" },
    [-447711397] = { model = "paragon", name = "Paragon", brand = "Enus", category = "sports" },
    [1181339704] = { model = "openwheel2", name = "DR1", brand = "Declasse", category = "openwheel" },
    [1550581940] = { model = "issi8", name = "Issi Rally", brand = "Weeny", category = "sports" },
    [6774487] = { model = "chimera", name = "Chimera", brand = "Nagasaki", category = "motorcycles" },
    [-233098306] = { model = "boxville2", name = "Boxville Go Postal", brand = "Brute", category = "vans" },
    [1993851908] = { model = "reever", name = "Reever", brand = "Western", category = "motorcycles" },
    [108773431] = { model = "coquette", name = "Coquette", brand = "Invetero", category = "sports" },
    [-988501280] = { model = "cheburek", name = "Cheburek", brand = "Rune", category = "sportsclassics" },
    [121658888] = { model = "boxville3", name = "Boxville Humane Labs", brand = "Brute", category = "vans" },
    [666166960] = { model = "baller6", name = "Baller LE LWB (Armored)", brand = "Gallivanter", category = "suvs" },
    [444171386] = { model = "boxville4", name = "Boxville Post OP", brand = "Brute", category = "vans" },
    [-119658072] = { model = "pony", name = "Pony", brand = "Brute", category = "vans" },
    [1491277511] = { model = "sanctus", name = "Sanctus", brand = "LCC", category = "motorcycles" },
    [1107404867] = { model = "peyote3", name = "Peyote Custom", brand = "Vapid", category = "sportsclassics" },
    [669204833] = { model = "virtue", name = "Virtue", brand = "Ocelot", category = "super" },
    [55628203] = { model = "faggio2", name = "Faggio", brand = "Pegassi", category = "motorcycles" },
    [1009171724] = { model = "impaler2", name = "Impaler Arena", brand = "Vapid", category = "muscle" },
    [-1233767450] = { model = "polgauntlet", name = "Gauntlet Interceptor", brand = "Bravado", category = "emergency" },
    [2006142190] = { model = "daemon", name = "Daemon", brand = "WMC", category = "motorcycles" },
    [-2119578145] = { model = "faction", name = "Faction", brand = "Willard", category = "muscle" },
    [-1800170043] = { model = "gauntlet", name = "Gauntlet", brand = "Bravado", category = "muscle" },
    [2046537925] = { model = "police", name = "Police Cruiser", brand = "Vapid", category = "emergency" },
    [500482303] = { model = "swinger", name = "Swinger", brand = "Ocelot", category = "sportsclassics" },
    [-1829802492] = { model = "pfister811", name = "811", brand = "Pfister", category = "super" },
    [-674927303] = { model = "raptor", name = "Raptor", brand = "BF", category = "sports" },
    [1537277726] = { model = "issi5", name = "Issi Future Shock", brand = "Weeny", category = "compacts" },
    [1026149675] = { model = "youga2", name = "Youga Classic", brand = "Bravado", category = "vans" },
    [1131912276] = { model = "bmx", name = "BMX", brand = "Bike", category = "cycles" },
    [448402357] = { model = "cruiser", name = "Cruiser", brand = "Bike", category = "cycles" },
    [48339065] = { model = "tiptruck", name = "Tipper", brand = "Brute", category = "industrial" },
    [117401876] = { model = "btype", name = "Roosevelt", brand = "Albany", category = "sportsclassics" },
    [970356638] = { model = "duster", name = "Duster", brand = "Western Company", category = "planes" },
    [-50547061] = { model = "cargobob", name = "Cargobob", brand = "Western Company", category = "helicopters" },
    [-1353081087] = { model = "vindicator", name = "Vindicator", brand = "Dinka", category = "motorcycles" },
    [903794909] = { model = "savestra", name = "Savestra", brand = "Annis", category = "sportsclassics" },
    [1492612435] = { model = "openwheel1", name = "BR8", brand = "Benefactor", category = "openwheel" },
    [1486521356] = { model = "youga4", name = "Youga Custom", brand = "Bravado", category = "vans" },
    [-291021213] = { model = "sultan3", name = "Sultan Classic Custom", brand = "Karin", category = "sports" },
    [-897824023] = { model = "inductor", name = "Inductor", brand = "Coil", category = "cycles" },
    [1448677353] = { model = "tropic2", name = "Tropic Yacht", brand = "Shitzu", category = "boats" },
    [-1685021548] = { model = "sabregt", name = "Sabre GT Turbo", brand = "Declasse", category = "muscle" },
    [741586030] = { model = "pranger", name = "Park Ranger", brand = "Declasse", category = "emergency" },
    [-808831384] = { model = "baller", name = "Baller", brand = "Gallivanter", category = "suvs" },
    [-49115651] = { model = "vamos", name = "Vamos", brand = "Declasse", category = "muscle" },
    [-1255452397] = { model = "schafter2", name = "Schafter", brand = "Benefactor", category = "sedans" },
    [-1269889662] = { model = "blazer3", name = "Blazer Hot Rod", brand = "Nagasaki", category = "offroad" },
    [-431692672] = { model = "panto", name = "Panto", brand = "Benefactor", category = "compacts" },
    [-999594302] = { model = "eurosX32", name = "Euros X32", brand = "Annis", category = "sports" },
    [-1372848492] = { model = "kuruma", name = "Kuruma", brand = "Karin", category = "sports" },
    [-2064372143] = { model = "mesa3", name = "Mesa Merryweather", brand = "Canis", category = "offroad" },
    [1747439474] = { model = "stockade", name = "Stockade", brand = "Brute", category = "commercial" },
    [740289177] = { model = "vagrant", name = "Vagrant", brand = "Maxwell", category = "offroad" },
    [-836512833] = { model = "fixter", name = "Fixter", brand = "Bike", category = "cycles" },
    [-1673356438] = { model = "velum", name = "Velum", brand = "JoBuilt", category = "planes" },
    [628003514] = { model = "issi4", name = "Issi Arena", brand = "Weeny", category = "compacts" },
    [-1214293858] = { model = "luxor2", name = "Luxor Deluxe", brand = "Buckingham", category = "planes" },
    [-1659004814] = { model = "conada2", name = "Weaponized Conada", brand = "Buckingham", category = "helicopters" },
    [447548909] = { model = "volatol", name = "Volatol", brand = "Unknown", category = "planes" },
    [-27326686] = { model = "deathbike", name = "Deathbike Apocalypse", brand = "Deathbike", category = "motorcycles" },
    [-159126838] = { model = "innovation", name = "Innovation", brand = "LLC", category = "motorcycles" },
    [-741120335] = { model = "asterope2", name = "Asterope GZ", brand = "Karin", category = "sedans" },
    [-1810806490] = { model = "seminole2", name = "Seminole Frontier", brand = "Canis", category = "suvs" },
    [-377465520] = { model = "penumbra", name = "Penumbra", brand = "Maibatsu", category = "sports" },
    [-488123221] = { model = "predator", name = "Police Predator", brand = "Unknown", category = "emergency" },
    [-784816453] = { model = "mixer", name = "Mixer", brand = "HVY", category = "industrial" },
    [-773802025] = { model = "poldominator10", name = "Dominator FX Interceptor", brand = "Vapid", category = "emergency" },
    [1221512915] = { model = "seminole", name = "Seminole", brand = "Canis", category = "suvs" },
    [904750859] = { model = "mule", name = "Mule", brand = "Maibatsu", category = "commercial" },
    [621481054] = { model = "luxor", name = "Luxor", brand = "Buckingham", category = "planes" },
    [629969764] = { model = "astron", name = "Astron", brand = "Pfister", category = "sedans" },
    [-1122289213] = { model = "zion", name = "Zion", brand = "Übermacht", category = "coupes" },
    [-1444856003] = { model = "policet3", name = "Burrito (Bail Enforcement)", brand = "Declasse", category = "emergency" },
    [1777363799] = { model = "washington", name = "Washington", brand = "Albany", category = "sedans" },
    [-1485523546] = { model = "schafter3", name = "Schafter V12", brand = "Benefactor", category = "sports" },
    [-1254331310] = { model = "minitank", name = "RC Tank", brand = "Unknown", category = "military" },
    [268758436] = { model = "tulip2", name = "Tulip M-100", brand = "Declasse", category = "muscle" },
    [1593933419] = { model = "seasparrow3", name = "Sparrow (Prop)", brand = "Unknown", category = "helicopters" },
    [165968051] = { model = "buffalo5", name = "Buffalo EVX", brand = "Bravado", category = "muscle" },
    [-537896628] = { model = "caddy2", name = "Caddy (Civilian)", brand = "Nagasaki", category = "utility" },
    [-2118308144] = { model = "avenger", name = "Avenger", brand = "Mammoth", category = "planes" },
    [1456744817] = { model = "tulip", name = "Tulip", brand = "Declasse", category = "muscle" },
    [1181327175] = { model = "akula", name = "Akula", brand = "Unknown", category = "helicopters" },
    [196747873] = { model = "elegy", name = "Elegy Retro Custom", brand = "Annis", category = "sports" },
    [1452003510] = { model = "polimpaler6", name = "Impaler LX Cruiser", brand = "Declasse", category = "emergency" },
    [-1205801634] = { model = "blade", name = "Blade", brand = "Vapid", category = "muscle" },
    [1349725314] = { model = "sentinel", name = "Sentinel", brand = "Übermacht", category = "coupes" },
    [758895617] = { model = "ztype", name = "Z-Type", brand = "Truffade", category = "sportsclassics" },
    [-2128233223] = { model = "blazer", name = "Blazer", brand = "Annis", category = "offroad" },
    [-1683328900] = { model = "sheriff", name = "Sheriff SUV", brand = "Declasse", category = "emergency" },
    [579912970] = { model = "warrener2", name = "Warrener HKR", brand = "Vulcar", category = "sedans" },
    [-2137348917] = { model = "phantom", name = "Phantom", brand = "Jobuilt", category = "commercial" },
    [960812448] = { model = "furia", name = "Furia", brand = "Grotti", category = "super" },
    [782665360] = { model = "rhino", name = "Rhino Tank", brand = "Unknown", category = "military" },
    [-609625092] = { model = "vortex", name = "Vortex", brand = "Pegassi", category = "motorcycles" },
    [1337041428] = { model = "serrano", name = "Serrano", brand = "Benefactor", category = "suvs" },
    [850991848] = { model = "biff", name = "Biff", brand = "Brute", category = "commercial" },
    [-1883869285] = { model = "premier", name = "Premier", brand = "Declasse", category = "sedans" },
    [1254014755] = { model = "caracara", name = "Caracara", brand = "Vapid", category = "offroad" },
    [-10917683] = { model = "lm87", name = "LM87", brand = "Benefactor", category = "super" },
    [-1790546981] = { model = "faction2", name = "Faction Rider", brand = "Willard", category = "muscle" },
    [802856453] = { model = "monstrociti", name = "MonstroCiti", brand = "Maibatsu", category = "offroad" },
    [-442313018] = { model = "towtruck2", name = "Tow Truck (Small)", brand = "Vapid", category = "utility" },
    [-1894894188] = { model = "surge", name = "Surge", brand = "Cheval", category = "sedans" },
    [321739290] = { model = "crusader", name = "Crusader", brand = "Canis", category = "military" },
    [1560980623] = { model = "airtug", name = "Airtug", brand = "HVY", category = "utility" },
    [-2130482718] = { model = "dump", name = "Dump Truck", brand = "HVY", category = "industrial" },
    [1841130506] = { model = "retinue", name = "Retinue", brand = "Vapid", category = "sportsclassics" },
    [-482719877] = { model = "italigtb2", name = "Itali GTB Custom", brand = "Progen", category = "super" },
    [67753863] = { model = "yosemite3", name = "Yosemite Rancher", brand = "Declasse", category = "offroad" },
    [1488164764] = { model = "paradise", name = "Paradise", brand = "Bravado", category = "vans" },
    [-982130927] = { model = "turismo2", name = "Turismo Classic", brand = "Grotti", category = "sportsclassics", backengine = true },
    [884422927] = { model = "habanero", name = "Habanero", brand = "Emperor", category = "suvs" },
    [456714581] = { model = "policet", name = "Police Transporter", brand = "Vapid", category = "emergency" },
    [-1912017790] = { model = "wastelander", name = "Wastelander", brand = "MTL", category = "service" },
    [274946574] = { model = "tenf2", name = "10F Widebody", brand = "Obey", category = "sports" },
    [-1924800695] = { model = "impaler3", name = "Impaler Future Shock", brand = "Vapid", category = "muscle" },
    [301304410] = { model = "stryder", name = "Stryder", brand = "Nagasaki", category = "motorcycles" },
    [1283517198] = { model = "airbus", name = "Airport Bus", brand = "Brute", category = "service" },
    [1343932732] = { model = "mule5", name = "Mule (Heist)", brand = "Maibatsu", category = "commercial" },
    [943752001] = { model = "pony2", name = "Pony (Smoke on the water)", brand = "Brute", category = "vans" },
    [1043222410] = { model = "tula", name = "Tula", brand = "Mammoth", category = "planes" },
    [-1146969353] = { model = "scarab", name = "Scarab", brand = "HVY", category = "military" },
    [822018448] = { model = "defiler", name = "Defiler", brand = "Shitzu", category = "motorcycles" },
    [-1461482751] = { model = "ninef2", name = "9F Cabrio", brand = "Obey", category = "sports" },
    [-121446169] = { model = "kamacho", name = "Kamacho", brand = "Canis", category = "offroad" },
    [1621617168] = { model = "cargobob2", name = "Cargobob Jetsam", brand = "Western Company", category = "helicopters" },
    [-1845487887] = { model = "volatus", name = "Volatus", brand = "Buckingham", category = "helicopters" },
    [-838099166] = { model = "landstalker2", name = "Landstalker XL", brand = "Dundreary", category = "suvs" },
    [-1627000575] = { model = "police2", name = "Police Buffalo", brand = "Vapid", category = "emergency" },
    [368211810] = { model = "cargoplane", name = "Cargo Plane", brand = "JoBuilt", category = "planes" },
    [1706945532] = { model = "ruiner4", name = "Ruiner ZZ-8", brand = "Imponte", category = "muscle" },
    [1127861609] = { model = "tribike", name = "Whippet Race Bike", brand = "Bike", category = "cycles" },
    [784565758] = { model = "coquette3", name = "Coquette BlackFin", brand = "Invetero", category = "muscle" },
    [400514754] = { model = "squalo", name = "Squalo", brand = "Shitzu", category = "boats" },
    [1531094468] = { model = "tornado2", name = "Tornado Convertible", brand = "Declasse", category = "sportsclassics" },
    [408825843] = { model = "outlaw", name = "Outlaw", brand = "Nagasaki", category = "offroad" },
    [-1291952903] = { model = "entityxf", name = "Entity XF", brand = "Överflöd", category = "super" },
    [394110044] = { model = "jb7002", name = "JB 700W", brand = "Dewbauchee", category = "sportsclassics" },
    [-1450650718] = { model = "prairie", name = "Prairie", brand = "Bollokan", category = "compacts" },
    [1502869817] = { model = "trailerlarge", name = "Mobile Operations Center", brand = "Unknown", category = "military" },
    [345756458] = { model = "pbus2", name = "Festival Bus", brand = "Unknown", category = "service" },
    [-825837129] = { model = "vigero", name = "Vigero", brand = "Declasse", category = "muscle" },
    [-1775728740] = { model = "granger", name = "Granger", brand = "Declasse", category = "suvs" },
    [-159073155] = { model = "yosemite4", name = "Yosemite 1500", brand = "Declasse", category = "offroad" },
    [-616331036] = { model = "seashark2", name = "Seashark Lifeguard", brand = "Speedophile", category = "emergency" },
    [-960289747] = { model = "cablecar", name = "Cable Car", brand = "Unknown", category = "service" },
    [1373123368] = { model = "warrener", name = "Warrener", brand = "Vulcar", category = "sedans" },
    [1456336509] = { model = "vstr", name = "V-STR", brand = "Albany", category = "sports" },
    [1861786828] = { model = "longfin", name = "Longfin", brand = "Shitzu", category = "boats" },
    [359875117] = { model = "baller7", name = "Baller ST", brand = "Gallivanter", category = "sedans" },
    [-1933242328] = { model = "broadway", name = "Broadway", brand = "Classique", category = "coupes" },
    [841808271] = { model = "rhapsody", name = "Rhapsody", brand = "Declasse", category = "compacts" },
    [1591739866] = { model = "deveste", name = "Deveste", brand = "Principe", category = "super" },
    [310284501] = { model = "dynasty", name = "Dynasty", brand = "Weeny", category = "sportsclassics" },
    [728350375] = { model = "benson2", name = "Benson (Cluckin Bell)", brand = "Vapid", category = "commercial" },
    [-2122757008] = { model = "stunt", name = "Mallard", brand = "Western Company", category = "planes" },
    [-1041692462] = { model = "banshee", name = "Banshee", brand = "Bravado", category = "sports" },
    [-2098954619] = { model = "club", name = "Club", brand = "BF", category = "compacts" },
    [-1647941228] = { model = "fbi2", name = "FIB Granger", brand = "Declasse", category = "emergency" },
    [-1404136503] = { model = "daemon2", name = "Daemon Custom", brand = "Western", category = "motorcycles" },
    [165154707] = { model = "miljet", name = "Miljet", brand = "Buckingham", category = "planes" },
    [1886268224] = { model = "specter", name = "Specter", brand = "Dewbauchee", category = "sports" },
    [1384502824] = { model = "manchez3", name = "Manchez Scout Classic", brand = "Maibatsu", category = "motorcycles" },
    [-2048333973] = { model = "italigtb", name = "Itali GTB", brand = "Progen", category = "super" },
    [-893578776] = { model = "ruffian", name = "Ruffian", brand = "Pegassi", category = "motorcycles" },
    [-208911803] = { model = "jugular", name = "Jugular", brand = "Ocelot", category = "sports" },
    [1429622905] = { model = "brioso2", name = "Brioso 300", brand = "Grotti", category = "compacts" },
    [-768236378] = { model = "draugur", name = "Draugur", brand = "Declasse", category = "offroad" },
    [410882957] = { model = "kuruma2", name = "kuruma2", brand = "Karin2", category = "sports" },
    [219613597] = { model = "speedo4", name = "Speedo Custom", brand = "Vapid", category = "vans" },
    [-831834716] = { model = "btype2", name = "Franken Stange", brand = "Albany", category = "sportsclassics" },
    [2112052861] = { model = "pounder", name = "Pounder", brand = "MTL", category = "commercial" },
    [-1132721664] = { model = "imorgon", name = "Imorgon", brand = "Överflöd", category = "sports" },
    [1323778901] = { model = "emerus", name = "Emerus", brand = "Progen", category = "super" },
    [-239841468] = { model = "diablous", name = "Diablous", brand = "Principe", category = "motorcycles" },
    [2006667053] = { model = "voodoo", name = "Voodoo", brand = "Declasse", category = "muscle" },
    [-1193912403] = { model = "calico", name = "Calico GTF", brand = "Karin", category = "sports" },
    [-801550069] = { model = "cerberus", name = "Apocalypse Cerberus", brand = "MTL", category = "commercial" },
    [-1628000569] = { model = "poldorado", name = "Dorado Cruiser", brand = "Vapid", category = "emergency" },
    [868868440] = { model = "metrotrain", name = "Metro Train", brand = "Unknown", category = "service" },
    [1044954915] = { model = "skylift", name = "Skylift", brand = "HVY", category = "helicopters" },
    [-313185164] = { model = "autarch", name = "Autarch", brand = "Överflöd", category = "super" },
    [-1205689942] = { model = "riot", name = "Police Riot", brand = "Brute", category = "emergency" },
    [-326143852] = { model = "dukes2", name = "Duke O'Death", brand = "Imponte", category = "muscle" },
    [-891462355] = { model = "bati2", name = "Bati 801RR", brand = "Pegassi", category = "motorcycles" },
    [-440768424] = { model = "blazer4", name = "Blazer Sport", brand = "Annis", category = "offroad" },
    [-946047670] = { model = "paragon3", name = "Paragon S", brand = "Enus", category = "sports" },
    [-1071380347] = { model = "tampa2", name = "Drift Tampa", brand = "Declasse", category = "muscle" },
    [390201602] = { model = "cliffhanger", name = "Cliffhanger", brand = "Western", category = "motorcycles" },
    [719660200] = { model = "ruston", name = "Ruston", brand = "Hijak", category = "sports" },
    [301427732] = { model = "hexer", name = "Hexer", brand = "LCC", category = "motorcycles" },
    [-685276541] = { model = "emperor", name = "Emperor", brand = "Albany", category = "sedans" },
    [2049897956] = { model = "rapidgt3", name = "Rapid GT Classic", brand = "Dewbauchee", category = "sportsclassics" },
    [-2030171296] = { model = "cognoscenti", name = "Cognoscenti", brand = "Enus", category = "sedans" },
    [-2115793025] = { model = "avarus", name = "Avarus", brand = "LCC", category = "motorcycles" },
    [1945374990] = { model = "mule4", name = "Mule Custom", brand = "Maibatsu", category = "commercial" },
    [771711535] = { model = "submersible", name = "Submersible", brand = "Kraken Subs", category = "boats" },
    [-1006919392] = { model = "cutter", name = "Cutter", brand = "HVY", category = "industrial" },
    [-1606187161] = { model = "nightblade", name = "Nightblade", brand = "WMC", category = "motorcycles" },
    [-1961627517] = { model = "stretch", name = "Stretch", brand = "Dundreary", category = "sedans" },
    [-1983622024] = { model = "inductor2", name = "Junk Energy Inductor", brand = "Coil", category = "cycles" },
    [-749299473] = { model = "mogul", name = "Mogul", brand = "Mammoth", category = "planes" },
    [-114291515] = { model = "bati", name = "Bati 801", brand = "Pegassi", category = "motorcycles" },
    [-808457413] = { model = "patriot", name = "Patriot", brand = "Mammoth", category = "suvs" },
    [-1600252419] = { model = "valkyrie", name = "Valkyrie", brand = "Buckingham", category = "helicopters" },
    [1491375716] = { model = "forklift", name = "Forklift", brand = "HVY", category = "utility" },
    [-726768679] = { model = "seasparrow", name = "Sea Sparrow", brand = "Unknown", category = "helicopters" },
    [-1527436269] = { model = "cinquemila", name = "Lampadati", brand = "Cinquemila", category = "sedans" },
    [239897677] = { model = "raiju", name = "F-160 Raiju", brand = "Mammoth", category = "planes" },
    [-507495760] = { model = "schlagen", name = "Schlagen GT", brand = "Benefactor", category = "sports" },
    [290013743] = { model = "tropic", name = "Tropic", brand = "Shitzu", category = "boats" },
    [-566387422] = { model = "elegy2", name = "Elegy RH8", brand = "Annis", category = "sports" },
    [683047626] = { model = "contender", name = "Contender", brand = "Vapid", category = "suvs" },
    [-755532233] = { model = "imperator3", name = "Imperator Nightmare", brand = "Vapid", category = "muscle" },
    [627535535] = { model = "fcr", name = "FCR 1000", brand = "Pegassi", category = "motorcycles" },
    [-1295027632] = { model = "nimbus", name = "Nimbus", brand = "Buckingham", category = "planes" },
}